package main.dao;

import java.util.ArrayList;

public class helpersDao {

	public static ArrayList<String> paises() {
	    ArrayList<String> pais = new ArrayList<String>();
	    pais.add("AFGANISTAN");
	    pais.add("ALBANIA");
	    pais.add("ALEMANIA");
	    pais.add("ANDORRA");
	    pais.add("ANGOLA");
	    pais.add("ANGUILLA");
	    pais.add("ANTARTIDA");
	    pais.add("ANTIGUA Y BARBUDA");
	    pais.add("ANTILLAS HOLANDESAS");
	    pais.add("ARABIA SAUDI");
	    pais.add("ARGELIA");
	    pais.add("ARGENTINA");
	    pais.add("ARMENIA");
	    pais.add("ARUBA");
	    pais.add("AUSTRALIA");
	    pais.add("AUSTRIA");
	    pais.add("AZERBAIYAN");
	    pais.add("BAHAMAS");
	    pais.add("BAHREIN");
	    pais.add("BANGLADESH");
	    pais.add("BARBADOS");
	    pais.add("BELGICA");
	    pais.add("BELICE");
	    pais.add("BENIN");
	    pais.add("BERMUDAS");
	    pais.add("BIELORRUSIA");
	    pais.add("BIRMANIA");
	    pais.add("BOLIVIA");
	    pais.add("BOSNIA Y HERZEGOVINA");
	    pais.add("BOTSWANA");
	    pais.add("BRASIL");
	    pais.add("BRUNEI");
	    pais.add("BULGARIA");
	    pais.add("BURKINA FASO");
	    pais.add("BURUNDI");
	    pais.add("BUTAN");
	    pais.add("CABO VERDE");
	    pais.add("CAMBOYA");
	    pais.add("CAMERUN");
	    pais.add("CANADA");
	    pais.add("CHAD");
	    pais.add("CHILE");
	    pais.add("CHINA");
	    pais.add("CHIPRE");
	    pais.add("CIUDAD DEL VATICANO (SANTA SEDE)");
	    pais.add("COLOMBIA");
	    pais.add("COMORES");
	    pais.add("CONGO");
	    pais.add("REPUBLICA DEMOCRATICA DEL CONGO");
	    pais.add("COREA");
	    pais.add("COREA DEL NORTE");
	    pais.add("COSTA DE MARFIL");
	    pais.add("COSTA RICA");
	    pais.add("CROACIA (HRVATSKA)");
	    pais.add("CUBA");
	    pais.add("DINAMARCA");
	    pais.add("DJIBOUTI");
	    pais.add("DOMINICA");
	    pais.add("ECUADOR");
	    pais.add("EGIPTO");
	    pais.add("EL SALVADOR");
	    pais.add("EMIRATOS ARABES UNIDOS");
	    pais.add("ERITREA");
	    pais.add("ESLOVENIA");
	    pais.add("ESPAÃÂA");
	    pais.add("ESTADOS UNIDOS");
	    pais.add("ESTONIA");
	    pais.add("ETIOPIA");
	    pais.add("FIJI");
	    pais.add("FILIPINAS");
	    pais.add("FINLANDIA");
	    pais.add("FRANCIA");
	    pais.add("GABON");
	    pais.add("GAMBIA");
	    pais.add("GEORGIA");
	    pais.add("GHANA");
	    pais.add("GIBRALTAR");
	    pais.add("GRANADA");
	    pais.add("GRECIA");
	    pais.add("GROENLANDIA");
	    pais.add("GUADALUPE");
	    pais.add("GUAM");
	    pais.add("GUATEMALA");		
	    pais.add("GUAYANA");			
	    pais.add("GUAYANA FRANCESA");
	    pais.add("GUINEA");			
	    pais.add("GUINEA ECUATORIAL");
	    pais.add("GUINEA-BISSAU");		
	    pais.add("HAITI");			
	    pais.add("HONDURAS");		
	    pais.add("HUNGRIA");		
	    pais.add("INDIA");			
	    pais.add("INDONESIA");		
	    pais.add("IRAK");				
	    pais.add("IRAN");				
	    pais.add("IRLANDA");			
	    pais.add("ISLA BOUVET");		
	    pais.add("ISLA DE CHRISTMAS");
	    pais.add("ISLANDIA");
	    pais.add("ISLAS CAIMAN");
	    pais.add("ISLAS COOK");
	    pais.add("ISLAS DE COCOS O KEELING");
	    pais.add("ISLAS FAROE");
	    pais.add("ISLAS HEARD Y MCDONALD");
	    pais.add("ISLAS MALVINAS");
	    pais.add("ISLAS MARIANAS DEL NORTE");
	    pais.add("ISLAS MARSHALL");
	    pais.add("ISLAS MENORES DE ESTADOS UNIDOS");
	    pais.add("ISLAS PALAU");
	    pais.add("ISLAS SALOMON");
	    pais.add("ISLAS SVALBARD Y JAN MAYEN");
	    pais.add("ISLAS TOKELAU");
	    pais.add("ISLAS TURKS Y CAICOS");
	    pais.add("ISLAS VIRGENES (EEUU)");
	    pais.add("ISLAS VIRGENES (REINO UNIDO)");
	    pais.add("ISLAS WALLIS Y FUTUNA");
	    pais.add("ISRAEL");
	    pais.add("ITALIA");
	    pais.add("JAMAICA");
	    pais.add("JAPON");
	    pais.add("JORDANIA");
	    pais.add("KAZAJISTAN");
	    pais.add("KENIA");
	    pais.add("KIRGUIZISTAN");
	    pais.add("KIRIBATI");
	    pais.add("KUWAIT");
	    pais.add("LAOS");
	    pais.add("LESOTHO");
	    pais.add("LETONIA");
	    pais.add("LIBANO");
	    pais.add("LIBERIA");
	    pais.add("LIBIA");
	    pais.add("LIECHTENSTEIN");
	    pais.add("LITUANIA");
	    pais.add("LUXEMBURGO");
	    pais.add("EX-REPUBLICA YUGOSLAVA DE MACEDONIA");
	    pais.add("MADAGASCAR");
	    pais.add("MALASIA");
	    pais.add("MALAWI");
	    pais.add("MALDIVAS");
	    pais.add("MALI");
	    pais.add("MALTA");
	    pais.add("MARRUECOS");
	    pais.add("MARTINICA");
	    pais.add("MAURICIO");
	    pais.add("MAURITANIA");
	    pais.add("MAYOTTE");
	    pais.add("MEXICO");
	    pais.add("MICRONESIA");
	    pais.add("MOLDAVIA");
	    pais.add("MONACO");
	    pais.add("MONGOLIA");
	    pais.add("MONTSERRAT");
	    pais.add("MOZAMBIQUE");
	    pais.add("NAMIBIA");
	    pais.add("NAURU");
	    pais.add("NEPAL");
	    pais.add("NICARAGUA");
	    pais.add("NIGER");
	    pais.add("NIGERIA");
	    pais.add("NIUE");
	    pais.add("NORFOLK");
	    pais.add("NNORUEGAO");
	    pais.add("NUEVA CALEDONIA");
	    pais.add("NUEVA ZELANDA");
	    pais.add("OMAN");
	    pais.add("PAISES BAJOS");
	    pais.add("PANAMA");
	    pais.add("PAPUA NUEVA GUINEA");
	    pais.add("PAKISTAN");
	    pais.add("PARAGUAY");
	    pais.add("PERU");
	    pais.add("PITCAIRN");
	    pais.add("POLINESIA FRANCESA");
	    pais.add("POLONIA");
	    pais.add("PORTUGAL");
	    pais.add("PUERTO RICO");
	    pais.add("QATAR");
	    pais.add("REINO UNIDO");
	    pais.add("EPUBLICA CENTROAFRICANA");
	    pais.add("REPUBLICA CHECA");
	    pais.add("REPUBLICA DE SUDAFRICA");
	    pais.add("REPUBLICA DOMINICANA");
	    pais.add("REPUBLICA ESLOVACA");
	    pais.add("REUNION");
	    pais.add("RUANDA");
	    pais.add("RUMANIA");
	    pais.add("RUSIA");
	    pais.add("SAHARA OCCIDENTAL");
	    pais.add("SAINT KITTS Y NEVIS");
	    pais.add("SAMOA");
	    pais.add("SAMOA AMERICANA");
	    pais.add("SAN MARINO");
	    pais.add("SAN VICENTE Y GRANADINAS");
	    pais.add("SANTA HELENA");
	    pais.add("SANTA LUCIA");
	    pais.add("SANTO TOME Y PRINCIPE");
	    pais.add("SENEGAL");
	    pais.add("SEYCHELLES");
	    pais.add("SIERRA LEONA");
	    pais.add("SINGAPUR");
	    pais.add("SIRIA");
	    pais.add("SOMALIA");
	    pais.add("SRI LANKA");
	    pais.add("ST PIERRE Y MIQUELON");
	    pais.add("SUAZILANDIA");
	    pais.add("SUDAN");
	    pais.add("SUECIA");
	    pais.add("SUIZA");
	    pais.add("SURINAM");
	    pais.add("TAILANDIA");
	    pais.add("TAIWAN");
	    pais.add("TANZANIA");
	    pais.add("TAYIKISTAN");
	    pais.add("TERRITORIOS FRANCESES DEL SUR");
	    pais.add("TIMOR ORIENTAL");
	    pais.add("TOGO");
	    pais.add("TONGA");
	    pais.add("TRINIDAD Y TOBAGO");
	    pais.add("TUNEZ");
	    pais.add("TURKMENISTAN");
	    pais.add("TURQUIA");
	    pais.add("TUVALU");
	    pais.add("UCRANIA");
	    pais.add("UGANDA");
	    pais.add("URUGUAY");
	    pais.add("UZBEKISTAN");
	    pais.add("VANUATU");
	    pais.add("VENEZUELA");
	    pais.add("VIETNAM");
	    pais.add("YEMEN");
	    pais.add("YUGOSLAVIA");
	    pais.add("ZAMBIA");
	    pais.add("ZIMBABUE");	   
	    return pais;
	  }
	
}

